"""Simple TTL-based disk cache for API responses.

Security note: Uses pickle for DataFrame serialization. This cache only stores
data generated by our own code (yfinance responses, computed signals). It never
deserializes untrusted external input.
"""
import hashlib
import logging
import pickle
from datetime import datetime, timedelta
from pathlib import Path
from stockpulse.config.settings import get_config

logger = logging.getLogger(__name__)
_CACHE_DIR = Path(__file__).resolve().parent.parent.parent / "outputs" / ".cache" / "data"

def _cache_path(key: str) -> Path:
    hashed = hashlib.md5(key.encode()).hexdigest()
    return _CACHE_DIR / f"{hashed}.pkl"

def get_cached(key: str):
    path = _cache_path(key)
    if not path.exists():
        return None
    try:
        with open(path, "rb") as f:
            entry = pickle.load(f)
        ttl = timedelta(minutes=get_config()["cache_ttl_minutes"])
        if datetime.now() - entry["time"] < ttl:
            return entry["data"]
    except Exception:
        logger.debug("Cache miss (corrupt) for %s", key)
    return None

def set_cached(key: str, data) -> None:
    _CACHE_DIR.mkdir(parents=True, exist_ok=True)
    path = _cache_path(key)
    with open(path, "wb") as f:
        pickle.dump({"time": datetime.now(), "data": data}, f)


def cleanup_expired_cache() -> int:
    """Remove expired cache files from disk. Returns count of files removed."""
    if not _CACHE_DIR.exists():
        return 0

    removed = 0
    ttl = timedelta(minutes=get_config()["cache_ttl_minutes"])
    now = datetime.now()

    for path in _CACHE_DIR.glob("*.pkl"):
        try:
            with open(path, "rb") as f:
                entry = pickle.load(f)
            if now - entry["time"] > ttl * 3:  # remove if 3x expired
                path.unlink()
                removed += 1
        except Exception:
            # Corrupt file — remove it
            try:
                path.unlink()
                removed += 1
            except Exception:
                pass

    return removed
