"""Daily markdown and JSON report generators."""
import json
import logging
from datetime import datetime
from pathlib import Path
from stockpulse.config.settings import get_config

logger = logging.getLogger(__name__)

def _ensure_dirs():
    cfg = get_config()
    reports_dir = Path(cfg["outputs_dir"]) / "reports"
    json_dir = Path(cfg["outputs_dir"]) / "json"
    reports_dir.mkdir(parents=True, exist_ok=True)
    json_dir.mkdir(parents=True, exist_ok=True)
    return reports_dir, json_dir

def _generate_portfolio_section() -> tuple[list[str], dict | None]:
    """Generate portfolio P&L section for reports."""
    try:
        from stockpulse.portfolio.tracker import get_portfolio_status
        status = get_portfolio_status()
        if not status["positions"]:
            return [], None

        lines = [
            "## Portfolio P&L",
            "",
            f"**Total P&L: ${status['total_pnl']:+,.2f} ({status['total_pnl_pct']:+.2f}%)**",
            f"**Invested: ${status['total_invested']:,.2f} | Current: ${status['total_current']:,.2f}**",
            "",
            "| Ticker | Shares | Entry | Current | P&L % | P&L $ |",
            "|--------|--------|-------|---------|-------|-------|",
        ]
        for pos in status["positions"]:
            emoji = "📈" if pos["pnl"] >= 0 else "📉"
            lines.append(
                f"| {emoji} {pos['ticker']} | {pos['shares']} | "
                f"${pos['entry_price']:.2f} | ${pos['current_price']:.2f} | "
                f"{pos['pnl_pct']:+.2f}% | ${pos['pnl']:+,.2f} |"
            )
        lines.append("")
        return lines, status
    except Exception:
        logger.debug("Portfolio section generation failed")
        return [], None


def generate_morning_report(recommendations: list[dict]) -> str:
    reports_dir, json_dir = _ensure_dirs()
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"{date_str}-morning.md"
    json_path = json_dir / f"{date_str}-morning.json"
    buys = [r for r in recommendations if r["action"] == "BUY"]
    sells = [r for r in recommendations if r["action"] == "SELL"]
    holds = [r for r in recommendations if r["action"] == "HOLD"]
    lines = [f"# StockPulse Morning Scan -- {date_str}", "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S ET')}",
        f"**Tickers scanned:** {len(recommendations)}",
        f"**BUY signals:** {len(buys)} | **SELL signals:** {len(sells)} | **HOLD:** {len(holds)}",
        "", "---", "", "## Top 10 Opportunities", "",
        "| Ticker | Action | Confidence | Composite | Thesis |",
        "|--------|--------|------------|-----------|--------|"]
    top10 = sorted(recommendations, key=lambda r: abs(r["composite_score"]), reverse=True)[:10]
    for r in top10:
        thesis_short = r["thesis"][:80] + "..." if len(r["thesis"]) > 80 else r["thesis"]
        lines.append(f"| {r['ticker']} | {r['action']} | {r['confidence']}% | {r['composite_score']:.1f} | {thesis_short} |")
    lines.append("")
    if buys:
        lines.append("## BUY Signals")
        lines.append("")
        for r in sorted(buys, key=lambda x: x["confidence"], reverse=True):
            lines.extend([f"### {r['ticker']} -- BUY (confidence: {r['confidence']}%)",
                f"- **Thesis:** {r['thesis']}", f"- **Technical:** {r['technical_summary']}",
                f"- **Catalysts:** {r['catalyst_summary']}", f"- **Invalidation:** {r['invalidation']}", ""])
    if sells:
        lines.append("## SELL Signals")
        lines.append("")
        for r in sorted(sells, key=lambda x: x["confidence"], reverse=True):
            lines.extend([f"### {r['ticker']} -- SELL (confidence: {r['confidence']}%)",
                f"- **Thesis:** {r['thesis']}", f"- **Technical:** {r['technical_summary']}",
                f"- **Invalidation:** {r['invalidation']}", ""])
    # Signal performance section
    try:
        from stockpulse.research.tracker import get_performance_report
        perf_lines = get_performance_report()
        if perf_lines:
            lines.append("")
            lines.append(perf_lines)
            lines.append("")
    except Exception:
        pass
    portfolio_lines, portfolio_data = _generate_portfolio_section()
    if portfolio_lines:
        lines.extend(portfolio_lines)
    # Add to JSON too
    lines.extend(["---", "*Generated by StockPulse -- research only, not financial advice.*"])
    report_path.write_text("\n".join(lines))
    logger.info("Morning report written to %s", report_path)
    json_data = {"type": "morning_scan", "date": date_str, "timestamp": datetime.now().isoformat(),
        "total_scanned": len(recommendations), "buy_count": len(buys), "sell_count": len(sells), "hold_count": len(holds),
        "recommendations": [{k: v for k, v in r.items() if k != "signals"} for r in recommendations]}
    if portfolio_data:
        json_data["portfolio"] = portfolio_data
    json_path.write_text(json.dumps(json_data, indent=2, default=str))
    return str(report_path)

def generate_eod_report(recommendations: list[dict]) -> str:
    reports_dir, json_dir = _ensure_dirs()
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"{date_str}-eod.md"
    json_path = json_dir / f"{date_str}-eod.json"
    lines = [f"# StockPulse EOD Recap -- {date_str}", "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S ET')}",
        f"**Tickers in report:** {len(recommendations)}", "", "---", "", "## Summary", "",
        "| Ticker | Action | Confidence | Score |", "|--------|--------|------------|-------|"]
    for r in sorted(recommendations, key=lambda x: abs(x["composite_score"]), reverse=True)[:20]:
        lines.append(f"| {r['ticker']} | {r['action']} | {r['confidence']}% | {r['composite_score']:.1f} |")
    lines.append("")
    # Signal performance section
    try:
        from stockpulse.research.tracker import get_performance_report
        perf_lines = get_performance_report()
        if perf_lines:
            lines.append("")
            lines.append(perf_lines)
            lines.append("")
    except Exception:
        pass
    portfolio_lines, portfolio_data = _generate_portfolio_section()
    if portfolio_lines:
        lines.extend(portfolio_lines)
    lines.extend(["---", "*Generated by StockPulse -- research only, not financial advice.*"])
    report_path.write_text("\n".join(lines))
    json_data = {"type": "eod_recap", "date": date_str, "timestamp": datetime.now().isoformat(),
        "recommendations": [{k: v for k, v in r.items() if k != "signals"} for r in recommendations]}
    if portfolio_data:
        json_data["portfolio"] = portfolio_data
    json_path.write_text(json.dumps(json_data, indent=2, default=str))
    return str(report_path)
