"""Daily markdown and JSON report generators."""
import json
import logging
from datetime import datetime
from pathlib import Path
from stockpulse.config.settings import get_config

logger = logging.getLogger(__name__)

def _ensure_dirs():
    cfg = get_config()
    reports_dir = Path(cfg["outputs_dir"]) / "reports"
    json_dir = Path(cfg["outputs_dir"]) / "json"
    reports_dir.mkdir(parents=True, exist_ok=True)
    json_dir.mkdir(parents=True, exist_ok=True)
    return reports_dir, json_dir

def generate_morning_report(recommendations: list[dict]) -> str:
    reports_dir, json_dir = _ensure_dirs()
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"{date_str}-morning.md"
    json_path = json_dir / f"{date_str}-morning.json"
    buys = [r for r in recommendations if r["action"] == "BUY"]
    sells = [r for r in recommendations if r["action"] == "SELL"]
    holds = [r for r in recommendations if r["action"] == "HOLD"]
    lines = [f"# StockPulse Morning Scan -- {date_str}", "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S ET')}",
        f"**Tickers scanned:** {len(recommendations)}",
        f"**BUY signals:** {len(buys)} | **SELL signals:** {len(sells)} | **HOLD:** {len(holds)}",
        "", "---", "", "## Top 10 Opportunities", "",
        "| Ticker | Action | Confidence | Composite | Thesis |",
        "|--------|--------|------------|-----------|--------|"]
    top10 = sorted(recommendations, key=lambda r: abs(r["composite_score"]), reverse=True)[:10]
    for r in top10:
        thesis_short = r["thesis"][:80] + "..." if len(r["thesis"]) > 80 else r["thesis"]
        lines.append(f"| {r['ticker']} | {r['action']} | {r['confidence']}% | {r['composite_score']:.1f} | {thesis_short} |")
    lines.append("")
    if buys:
        lines.append("## BUY Signals")
        lines.append("")
        for r in sorted(buys, key=lambda x: x["confidence"], reverse=True):
            lines.extend([f"### {r['ticker']} -- BUY (confidence: {r['confidence']}%)",
                f"- **Thesis:** {r['thesis']}", f"- **Technical:** {r['technical_summary']}",
                f"- **Catalysts:** {r['catalyst_summary']}", f"- **Invalidation:** {r['invalidation']}", ""])
    if sells:
        lines.append("## SELL Signals")
        lines.append("")
        for r in sorted(sells, key=lambda x: x["confidence"], reverse=True):
            lines.extend([f"### {r['ticker']} -- SELL (confidence: {r['confidence']}%)",
                f"- **Thesis:** {r['thesis']}", f"- **Technical:** {r['technical_summary']}",
                f"- **Invalidation:** {r['invalidation']}", ""])
    lines.extend(["---", "*Generated by StockPulse -- research only, not financial advice.*"])
    report_path.write_text("\n".join(lines))
    logger.info("Morning report written to %s", report_path)
    json_data = {"type": "morning_scan", "date": date_str, "timestamp": datetime.now().isoformat(),
        "total_scanned": len(recommendations), "buy_count": len(buys), "sell_count": len(sells), "hold_count": len(holds),
        "recommendations": [{k: v for k, v in r.items() if k != "signals"} for r in recommendations]}
    json_path.write_text(json.dumps(json_data, indent=2, default=str))
    return str(report_path)

def generate_eod_report(recommendations: list[dict]) -> str:
    reports_dir, json_dir = _ensure_dirs()
    date_str = datetime.now().strftime("%Y-%m-%d")
    report_path = reports_dir / f"{date_str}-eod.md"
    json_path = json_dir / f"{date_str}-eod.json"
    lines = [f"# StockPulse EOD Recap -- {date_str}", "",
        f"**Generated:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S ET')}",
        f"**Tickers in report:** {len(recommendations)}", "", "---", "", "## Summary", "",
        "| Ticker | Action | Confidence | Score |", "|--------|--------|------------|-------|"]
    for r in sorted(recommendations, key=lambda x: abs(x["composite_score"]), reverse=True)[:20]:
        lines.append(f"| {r['ticker']} | {r['action']} | {r['confidence']}% | {r['composite_score']:.1f} |")
    lines.extend(["", "---", "*Generated by StockPulse -- research only, not financial advice.*"])
    report_path.write_text("\n".join(lines))
    json_data = {"type": "eod_recap", "date": date_str, "timestamp": datetime.now().isoformat(),
        "recommendations": [{k: v for k, v in r.items() if k != "signals"} for r in recommendations]}
    json_path.write_text(json.dumps(json_data, indent=2, default=str))
    return str(report_path)
